#
#        Build Battle 3 configuration file
#               Edit it by yourself
#          Read descriptions CAREFULLY
#   You don't want to break anything, do you?
#

# Locale of BB 3 language. By default it's english.
# Available localizations:
# default - uses messages from 'language.yml' file
# de - Deutsche sprache
# pl - Jezyk Polski
#    es - Idioma español
#
locale: default

# Enable boss bar for the game?
# Requires BossBarAPI for 1.8 users.
Boss-Bar-Enabled: false

# Should we hook into bungee cord? (If you wanna use arena per server option)
# You STILL need to use external addon for HUB server game signs
BungeeActivated: false

# Enable Inventory Manager for your games? (VERY USEFUL feature for MULTI ARENA)
# This saves inventory of players and restores it after player leaves arena.
# Saved elements: max health, health, food, experience, full inventory, armor contents, fire ticks, active potions
InventoryManager: false

# Basic game permissions
Basic-Permissions:
  # Permissions to edit/create arenas
  Arena-Edit-Permission: "buildbattle.editgames"
  # <arena> represents arena name (NOT MAP NAME!), for example: 'buildbattle.join.Build1'
  # use 'buildbattle.join.*' to enable access to all arenas
  Join-Permission: "buildbattle.join.<arena>"

# Should /bb leave command be disabled?
Disable-Leave-Command: false

# Total time of building in game
Build-Time-In-Seconds: 480

# Total time of voting per player plot
Voting-Time-In-Seconds: 20

# Total time of building in game in TEAM game mode
Team-Build-Time-In-Seconds: 540

# Total time of voting for themes before starting
Theme-Voting-Time-In-Seconds: 25

# Default floor material ID
Default-Floor-Material: 17

# Should mob spawning be disabled?
Disable-Mob-Spawning-Completely: true

# How many particle effects should have one spawned particle
Amount-One-Particle-Effect-Contains: 20

# Max amount of particles to spawn
Max-Amount-Particles: 25

# Time of refreshing particles
Particle-Refresh-Per-Tick: 10

# Should server be disabled after the game ends?
Bungee-Shutdown-On-End: false

# Offset of particles
Particle-Offset: 1

# Should win commands be activated?
Win-Commands-Activated: false

# Should end game commands be activated?
End-Game-Commands-Activated: true

# Should second place commands be activated?
Second-Place-Commands-Activated: false

# Should third place commands be activated?
Third-Place-Commands-Activated: false

# Should we save player names instead of their UUID's in database?
# Remember changing this value when there are already player records may break them!
Use-Name-Instead-Of-UUID-In-Database: false

# Max amount of mobs to spawn per plot
Mobs-Max-Amount-Per-Plot: 20

# Should we hide players outside game?
Hide-Players-Outside-Game: true

# Should scoreboard in game be disabled?
Disable-Scoreboard-Ingame: false

# Should we hook into Vault?
Hook-Into-Vault: false

# Time in lobby to wait before start
Lobby-Starting-Time: 60

# All game themes, type here everything you want your players to build.
Game-Themes:
- Bees
- Pirates
- Medieval
- Castle
- Love
- Hate
- Ugly

# Blacklisted item ID's, you can't use them while building.
Blacklisted-Items:
- 46
- 57

# Commands executed when player wins
# Use %PLAYER% placeholder to replace it with winner's name
Win-Commands:
- say %PLAYER% won the game!
- give %PLAYER% 1000

# Commands executed for second winner
Second-Place-Commands:
- say %PLAYER% become second
- give %PLAYER% 1000

# Commands executed for third winner
Third-Place-Commands:
- say %PLAYER% became third
- give %PLAYER% 1000

# Commands executed for every player after the game ends
End-Game-Commands:
- say %PLAYER% has played a game!
- give %PLAYER% 100

# Commands which can be executed while being in game
Whitelisted-Commands:
- me
- help

# Should blocks behind game signs change their color based on game state?
Signs-Block-States:
  Enabled: true
  # Block types: glass, clay, wool
  Block-Type: glass
  # Block colors.
  Colors:
    Waiting-For-Players:
      Glass: 0
      Clay: 0
      Wool: 0
    Starting:
      Glass: 4
      Clay: 4
      Wool: 4
    In-Game:
      Glass: 1
      Clay: 1
      Wool: 1
    Ending:
      Glass: 7
      Clay: 7
      Wool: 7
    Restarting:
      Glass: 15
      Clay: 15
      Wool: 15

Update-Notifier:
  # Should we check for updates on plugin start/after admin join?
  # You REALLY should have this true!
  Enabled: true
  # Should we inform you when beta version is out?
  # BETA IS NOT ALWAYS AS STABLE AS NORMAL RELEASE!
  Notify-Beta-Versions: true

# Disable or enable MySQL database here, see mysql.yml for more
DatabaseActivated: false

# Should plugin send 'debug spam' to console? IT CAN HELP IF YOU OCCUR SOME WEIRD BEHAVIOUR FROM PLUGIN
Debug: false

# Don't modify.
Version: 2

# No way! You've reached the end! But... where's the dragon!?
